/**
 * @file fm_presets.c
 * @brief Factory preset data for FM Percussion Synth
 *
 * Provides the definition of FM_PRESETS[] using C99 designated initializers
 * with string literals for .name (char array members).
 */

#include "fm_presets.h"

const fm_preset_t FM_PRESETS[NUM_OF_PRESETS] = {
    // Preset 0: "Deep Tribal"
    {
        .name = "Deep Tribal",
        .prob_kick = 100,
        .prob_snare = 80,
        .prob_metal = 60,
        .prob_perc = 70,
        .kick_sweep = 80,
        .kick_decay = 60,
        .snare_noise = 30,
        .snare_body = 70,
        .metal_inharm = 40,
        .metal_bright = 50,
        .perc_ratio = 50,
        .perc_var = 40,
        .lfo1_shape = 0,
        .lfo1_rate = 20,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 30,
        .lfo2_shape = 1,
        .lfo2_rate = 5,
        .lfo2_target = LFO_TARGET_INDEX,
        .lfo2_depth = 20,
        .env_shape = 20,
        .voice_index = 0,
        .resonant_morph = 2,
        .resonant_mode = RESONANT_MODE_BANDPASS,
        .resonant_res = 50,
        .resonant_center = 30,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 1: "Metal Storm"
    {
        .name = "Metal Storm",
        .prob_kick = 60,
        .prob_snare = 80,
        .prob_metal = 100,
        .prob_perc = 50,
        .kick_sweep = 40,
        .kick_decay = 30,
        .snare_noise = 60,
        .snare_body = 40,
        .metal_inharm = 80,
        .metal_bright = 90,
        .perc_ratio = 30,
        .perc_var = 60,
        .lfo1_shape = 6,
        .lfo1_rate = 60,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 20,
        .lfo2_shape = 4,
        .lfo2_rate = 80,
        .lfo2_target = LFO_TARGET_LFO1_PHASE,
        .lfo2_depth = 50,
        .env_shape = 5,
        .voice_index = 0,
        .resonant_morph = 90,
        .resonant_mode = RESONANT_MODE_PEAK,
        .resonant_res = 70,
        .resonant_center = 60,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 2: "ChordalPerc"
    {
        .name = "ChordalPerc",
        .prob_kick = 70,
        .prob_snare = 70,
        .prob_metal = 70,
        .prob_perc = 70,
        .kick_sweep = 50,
        .kick_decay = 50,
        .snare_noise = 40,
        .snare_body = 50,
        .metal_inharm = 30,
        .metal_bright = 40,
        .perc_ratio = 60,
        .perc_var = 50,
        .lfo1_shape = 2,
        .lfo1_rate = 30,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 40,
        .lfo2_shape = 2,
        .lfo2_rate = 15,
        .lfo2_target = LFO_TARGET_PITCH,
        .lfo2_depth = -30,
        .env_shape = 40,
        .voice_index = 0,
        .resonant_morph = 50,
        .resonant_mode = RESONANT_MODE_LOWPASS,
        .resonant_res = 30,
        .resonant_center = 20,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 3: "Phase Dance"
    {
        .name = "Phase Dance",
        .prob_kick = 80,
        .prob_snare = 60,
        .prob_metal = 80,
        .prob_perc = 60,
        .kick_sweep = 30,
        .kick_decay = 40,
        .snare_noise = 50,
        .snare_body = 60,
        .metal_inharm = 50,
        .metal_bright = 60,
        .perc_ratio = 40,
        .perc_var = 30,
        .lfo1_shape = 3,
        .lfo1_rate = 45,
        .lfo1_target = LFO_TARGET_LFO2_PHASE,
        .lfo1_depth = 70,
        .lfo2_shape = 5,
        .lfo2_rate = 30,
        .lfo2_target = LFO_TARGET_LFO1_PHASE,
        .lfo2_depth = 70,
        .env_shape = 30,
        .voice_index = 0,
        .resonant_morph = 25,
        .resonant_mode = RESONANT_MODE_HIGHPASS,
        .resonant_res = 40,
        .resonant_center = 40,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 4: "BipolarBass"
    {
        .name = "BipolarBass",
        .prob_kick = 100,
        .prob_snare = 40,
        .prob_metal = 30,
        .prob_perc = 50,
        .kick_sweep = 90,
        .kick_decay = 80,
        .snare_noise = 20,
        .snare_body = 30,
        .metal_inharm = 20,
        .metal_bright = 30,
        .perc_ratio = 30,
        .perc_var = 20,
        .lfo1_shape = 1,
        .lfo1_rate = 10,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = -50,
        .lfo2_shape = 0,
        .lfo2_rate = 25,
        .lfo2_target = LFO_TARGET_NONE,
        .lfo2_depth = 0,
        .env_shape = 10,
        .voice_index = 0,
        .resonant_morph = 10,
        .resonant_mode = RESONANT_MODE_LOWPASS,
        .resonant_res = 20,
        .resonant_center = 10,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 5: "Snare Roll"
    {
        .name = "Snare Roll",
        .prob_kick = 30,
        .prob_snare = 100,
        .prob_metal = 40,
        .prob_perc = 30,
        .kick_sweep = 20,
        .kick_decay = 30,
        .snare_noise = 80,
        .snare_body = 60,
        .metal_inharm = 30,
        .metal_bright = 40,
        .perc_ratio = 40,
        .perc_var = 30,
        .lfo1_shape = 1,
        .lfo1_rate = 90,
        .lfo1_target = LFO_TARGET_INDEX,
        .lfo1_depth = 60,
        .lfo2_shape = 1,
        .lfo2_rate = 45,
        .lfo2_target = LFO_TARGET_PITCH,
        .lfo2_depth = 20,
        .env_shape = 15,
        .voice_index = 0,
        .resonant_morph = 2,
        .resonant_mode = RESONANT_MODE_PEAK,
        .resonant_res = 60,
        .resonant_center = 70,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 6: "AmbientMetl"
    {
        .name = "AmbientMetl",
        .prob_kick = 40,
        .prob_snare = 50,
        .prob_metal = 100,
        .prob_perc = 60,
        .kick_sweep = 30,
        .kick_decay = 70,
        .snare_noise = 40,
        .snare_body = 50,
        .metal_inharm = 70,
        .metal_bright = 80,
        .perc_ratio = 50,
        .perc_var = 60,
        .lfo1_shape = 0,
        .lfo1_rate = 15,
        .lfo1_target = LFO_TARGET_ENV,
        .lfo1_depth = 40,
        .lfo2_shape = 8,
        .lfo2_rate = 40,
        .lfo2_target = LFO_TARGET_PITCH,
        .lfo2_depth = 20,
        .env_shape = 90,
        .voice_index = 0,
        .resonant_morph = 70,
        .resonant_mode = RESONANT_MODE_NOTCH,
        .resonant_res = 80,
        .resonant_center = 50,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 7: "Polyrhythm"
    {
        .name = "Polyrhythm",
        .prob_kick = 90,
        .prob_snare = 70,
        .prob_metal = 50,
        .prob_perc = 80,
        .kick_sweep = 50,
        .kick_decay = 50,
        .snare_noise = 50,
        .snare_body = 50,
        .metal_inharm = 50,
        .metal_bright = 50,
        .perc_ratio = 50,
        .perc_var = 50,
        .lfo1_shape = 4,
        .lfo1_rate = 35,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 30,
        .lfo2_shape = 7,
        .lfo2_rate = 55,
        .lfo2_target = LFO_TARGET_PITCH,
        .lfo2_depth = 30,
        .env_shape = 25,
        .voice_index = 0,
        .resonant_morph = 50,
        .resonant_mode = RESONANT_MODE_BANDPASS,
        .resonant_res = 50,
        .resonant_center = 30,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_PERC}},

    // Preset 8: "ResoKick"
    {
        .name = "ResoKick",
        .prob_kick = 100,
        .prob_snare = 0,
        .prob_metal = 0,
        .prob_perc = 0,
        .kick_sweep = 70,
        .kick_decay = 60,
        .snare_noise = 0,
        .snare_body = 0,
        .metal_inharm = 0,
        .metal_bright = 0,
        .perc_ratio = 0,
        .perc_var = 0,
        .lfo1_shape = 0,
        .lfo1_rate = 10,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 20,
        .lfo2_shape = 0,
        .lfo2_rate = 5,
        .lfo2_target = LFO_TARGET_NONE,
        .lfo2_depth = 0,
        .env_shape = 25,
        .voice_index = 8,
        .resonant_morph = 20,
        .resonant_mode = RESONANT_MODE_LOWPASS,
        .resonant_res = 40,
        .resonant_center = 15,
        .engine_map = {ENGINE_RESONANT, ENGINE_SNARE, ENGINE_KICK, ENGINE_PERC}},

    // Preset 9: "ResoTom"
    {
        .name = "ResoTom",
        .prob_kick = 0,
        .prob_snare = 0,
        .prob_metal = 0,
        .prob_perc = 100,
        .kick_sweep = 50,
        .kick_decay = 50,
        .snare_noise = 0,
        .snare_body = 0,
        .metal_inharm = 0,
        .metal_bright = 0,
        .perc_ratio = 50,
        .perc_var = 50,
        .lfo1_shape = 1,
        .lfo1_rate = 15,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 30,
        .lfo2_shape = 1,
        .lfo2_rate = 8,
        .lfo2_target = LFO_TARGET_INDEX,
        .lfo2_depth = 20,
        .env_shape = 35,
        .voice_index = 1,
        .resonant_morph = 20,
        .resonant_mode = RESONANT_MODE_BANDPASS,
        .resonant_res = 60,
        .resonant_center = 25,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_METAL, ENGINE_RESONANT}},

    // Preset 10: "ResoSnare"
    {
        .name = "ResoSnare",
        .prob_kick = 0,
        .prob_snare = 100,
        .prob_metal = 0,
        .prob_perc = 0,
        .kick_sweep = 0,
        .kick_decay = 0,
        .snare_noise = 50,
        .snare_body = 50,
        .metal_inharm = 0,
        .metal_bright = 0,
        .perc_ratio = 0,
        .perc_var = 0,
        .lfo1_shape = 2,
        .lfo1_rate = 20,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 40,
        .lfo2_shape = 2,
        .lfo2_rate = 10,
        .lfo2_target = LFO_TARGET_INDEX,
        .lfo2_depth = 30,
        .env_shape = 20,
        .voice_index = 3,
        .resonant_morph = 20,
        .resonant_mode = RESONANT_MODE_HIGHPASS,
        .resonant_res = 50,
        .resonant_center = 45,
        .engine_map = {ENGINE_KICK, ENGINE_RESONANT, ENGINE_METAL, ENGINE_PERC}},

    // Preset 11: "ResoMetal"
    {
        .name = "ResoMetal",
        .prob_kick = 0,
        .prob_snare = 0,
        .prob_metal = 100,
        .prob_perc = 0,
        .kick_sweep = 0,
        .kick_decay = 0,
        .snare_noise = 0,
        .snare_body = 0,
        .metal_inharm = 70,
        .metal_bright = 80,
        .perc_ratio = 0,
        .perc_var = 0,
        .lfo1_shape = 8,
        .lfo1_rate = 30,
        .lfo1_target = LFO_TARGET_PITCH,
        .lfo1_depth = 50,
        .lfo2_shape = 6,
        .lfo2_rate = 40,
        .lfo2_target = LFO_TARGET_INDEX,
        .lfo2_depth = 40,
        .env_shape = 10,
        .voice_index = 2,
        .resonant_morph = 20,
        .resonant_mode = RESONANT_MODE_PEAK,
        .resonant_res = 80,
        .resonant_center = 80,
        .engine_map = {ENGINE_KICK, ENGINE_SNARE, ENGINE_RESONANT, ENGINE_PERC}}
};
