/**
 * @brief High-precision NEON sine using Minimax & Cody-Waite range reduction.
 * Adapted from Julien Pommier's neon_mathfun.h
 * * Capable of handling massive phase deviations generated by high-index
 * FM modulation without catastrophic cancellation (aliasing/clicking).
 */
/* Copyright (C) 2011  Julien Pommier

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

  (this is the zlib license)
*/
#pragma once
#include <arm_neon.h>

fast_inline float32x4_t neon_sin(float32x4_t x) {
    float32x4_t sign_bit = x;

    // 1. Take absolute value
    x = vabsq_f32(x);

    // 2. Extract sign bit (0x80000000)
    sign_bit = vreinterpretq_f32_u32(vandq_u32(
        vreinterpretq_u32_f32(sign_bit),
        vdupq_n_u32(0x80000000)
    ));

    // 3. Scale by 4/Pi to determine the quadrant
    float32x4_t y = vmulq_f32(x, vdupq_n_f32(1.27323954473516f));

    // 4. Round to nearest even integer
    int32x4_t emm2 = vcvtq_s32_f32(y);
    emm2 = vaddq_s32(emm2, vdupq_n_s32(1));
    emm2 = vandq_s32(emm2, vdupq_n_s32(~1));
    y = vcvtq_f32_s32(emm2);

    // 5. Swap sign bit calculation based on quadrant
    int32x4_t emm0 = vandq_s32(emm2, vdupq_n_s32(4));
    emm0 = vshlq_n_s32(emm0, 29);
    float32x4_t swap_sign_bit = vreinterpretq_f32_s32(emm0);

    // Combine sign bits
    sign_bit = vreinterpretq_f32_u32(veorq_u32(
        vreinterpretq_u32_f32(sign_bit),
        vreinterpretq_u32_f32(swap_sign_bit)
    ));

    // 6. Polynomial selection mask (Sin vs Cos curve)
    uint32x4_t poly_mask = vreinterpretq_u32_s32(vceqq_s32(
        vandq_s32(emm2, vdupq_n_s32(2)),
        vdupq_n_s32(0)
    ));

    // ===============================================================
    // 7. Cody-Waite Range Reduction
    // Uses extended precision to prevent FM phase catastrophe
    // ===============================================================
    x = vmlaq_f32(x, y, vdupq_n_f32(-0.78515625f));
    x = vmlaq_f32(x, y, vdupq_n_f32(-2.4187564849853515625e-4f));
    x = vmlaq_f32(x, y, vdupq_n_f32(-3.77489497744594108e-8f));

    // Calculate z = x^2 for Taylor series
    float32x4_t z = vmulq_f32(x, x);

    // ===============================================================
    // 8. Minimax Polynomial Evaluations
    // ===============================================================
    // Sin polynomial
    float32x4_t y1 = vmlaq_f32(vdupq_n_f32(8.3321608736E-3f), z, vdupq_n_f32(-1.9515295891E-4f));
    y1 = vmlaq_f32(vdupq_n_f32(-1.6666654611E-1f), z, y1);
    y1 = vmlaq_f32(x, vmulq_f32(z, x), y1);

    // Cos polynomial
    float32x4_t y2 = vmlaq_f32(vdupq_n_f32(-1.388731625493765E-3f), z, vdupq_n_f32(2.443315711809948E-5f));
    y2 = vmlaq_f32(vdupq_n_f32(4.166664568298827E-2f), z, y2);
    y2 = vmlaq_f32(vdupq_n_f32(-0.5f), z, y2);
    y2 = vaddq_f32(vdupq_n_f32(1.0f), vmulq_f32(z, y2));

    // 9. Select curve and apply sign
    float32x4_t res = vbslq_f32(poly_mask, y1, y2);
    return vreinterpretq_f32_u32(veorq_u32(
        vreinterpretq_u32_f32(res),
        vreinterpretq_u32_f32(sign_bit)
    ));
}