"""
Constants, static names and formatting settings for the FPGA register-map
XML to C header generator.

The tool chain is made of four modules:
    config.py                  - this file: every tunable and fixed name
    printing.py                - functions writing the pieces of the header
    support_functions.py       - small helpers and the argument parser
    convert_xml_in_c_header.py - main: XML parsing and header building

Everything that is a matter of style or naming of the generated headers
(column widths, doxygen banners, fixed texts, names that cannot be derived
from the XML content) is collected here, so a layout change never requires
touching the logic.
"""
import os
from datetime import date
from lib.utils import get_root

# =====================================================================
# Defaults paths
# =====================================================================
DEFAULT_INPUT_PATH = str(get_root()) + os.path.sep + "submodules/fpga/xhw/modules"
DEFAULT_OUTPUT_PATH = str(get_root()) + os.path.sep + "fpgaInterface" + os.path.sep + "registerIf"
TEMP_OUTPUT_PATH = str(get_root()) + os.path.sep + "loc_ws" + os.path.sep + "tmp"
default_files = [
    "cell_configuration.xml",
    "cell_timing.xml",
    "dl_cluster_pb_schedule.xml",
    "dl_lowphy_cluster.xml",
    "prach_cluster_schedule.xml",
    "timer.xml",
    "ul_lowphy_cluster.xml",
    "pucch_accelerator_format_2_2a.xml",
    "pucch_accelerator_format_1_1a.xml",
    "ul_cluster_pb_schedule.xml",  # NOTE add new files here and new structures below!
    "top.xml",
]
DEFAULT_BASE_ADDR_FILE = (
    str(get_root()) + os.path.sep + "submodules/fpga/ip/nucleus_bd/nucleus_bd.tcl"
)

# =====================================================================
# tool identity / logging
# =====================================================================
TOOL_NAME = "convert_xml_in_c_header.py"
LOGGER_NAME = "generate_fpga_interface"
# python logging classic style, gives "INFO:generate_fpga_interface:..."
LOG_FORMAT = "%(levelname)s:%(name)s:%(message)s"

INFO_PARSING_OVER = "XML parsing is over, find the result file as:\n%s"
WARN_FILE_PROBLEM = "%s: %s"
WARN_PROBLEM_SUMMARY = "problems found while converting the following files: %s"

# =====================================================================
# input XML: tags of the pi3 register description schema
# =====================================================================
XML_NAMESPACE = "http://xhw-publisher.rsint.net/xml/pi3/1"

TAG_NAME = "name"
TAG_DESCRIPTION = "description"
TAG_ADDRESS_UNIT_BITS = "address_unit_bits"
TAG_DATA_BUS_WIDTH = "data_bus_width"

TAG_REGISTER = "register"
TAG_ADDRESS = "address_literal"
TAG_WIDTH = "width"
TAG_LENGTH = "length"                    # RAM implementation only
TAG_IMPLEMENTATION = "implementation"
TAG_MULTIPLY = "multiply"
TAG_MULTIPLY_OFFSET = "multiply_address_offset_literal"
TAG_MULTIPLY_START = "multiply_start_index"

TAG_SIGNAL = "signal"
TAG_BIT_MSB_LSB = "bit_msb_lsb"
TAG_SIGNAL_VALUE = "signal_value"
TAG_VALUE_LITERAL = "value_literal"

# top.xml only
TAG_SUBSYSTEM = "subsystem"
TAG_INSTANCE_NAME = "instance_name"
TAG_SYSTEM_NAME = "system_name"
TAG_BASE_ADDRESS = "base_address_literal"

IMPLEMENTATION_RAM = "RAM"

DEFAULT_DATA_BUS_WIDTH = 32              # bits
DEFAULT_ADDRESS_UNIT_BITS = 8            # bits

# =====================================================================
# fixed names of the input registers
# =====================================================================
# the two registers common to every module, in the expected order
COMMON_REGISTERS = ("MODULE_ID", "RESET")

# MODULE_ID signals whose value literals (stripped of "0x") are
# concatenated to build the <MODULE>_MODULE_ID define value,
# e.g. 0x10F + 0 + 0x01 + 0x03 -> 0x10F00103
MODULE_ID_SIGNALS = ("MODULE_ID", "INST_ID", "MAJOR_VERSION", "MINOR_VERSION")

# registers whose C names get the module name as prefix because the plain
# register name is too generic (LOGMASK -> TimerLogmask_u, CellTimingLogmask_u)
PREFIX_WITH_MODULE = ("LOGMASK",)

# =====================================================================
# generated header: fixed texts
# =====================================================================
AUTHOR = "Azcom"
COMPANY = "Azcomtech S.r.l - https://www.azcomtech.com/"
INGROUP = "FPGA_IF"
YEAR = str(date.today().year)
GENERATED_SUFFIX = " (automatically generated by " + TOOL_NAME + " script)"
HEADER_EXTENSION = ".h"

# banner row of every doxygen block
BANNER = " " + "*" * 60

FILE_HEADER_TEMPLATE = r"""/**
{banner}
 * \file  {file_name}
 *
 * \brief {brief}
 *                -- DO NOT EDIT MANUALLY --
 * \ingroup {ingroup}
 *
 * \author {author}
 *
 * \date   {year}
 *
 *  Copyright (C) {year} {company}
 *
 *  All Rights Reserved.
{banner}
*/

#pragma once
"""

# NOTE: the reference CommonAddresses.h has no "#pragma once" and a fixed
# multi line brief: both reproduced verbatim here
COMMON_ADDRESSES_HEADER_TEMPLATE = r"""/**
{banner}
 * \file  {file_name}
 *
 * \brief This file contains the C style macros definitions of the
 *  the memory address offset for the structures found in other XMLs
 *  (automatically generated by convert_xml_in_c_header.py script)
 *                -- DO NOT EDIT MANUALLY --
 * \ingroup {ingroup}
 *
 * \author {author}
 *
 * \date   {year}
 *
 *  Copyright (C) {year} {company}
 *
 *  All Rights Reserved.
{banner}
*/
"""

REGISTER_COMMENT_TEMPLATE = r"""/**
{banner}
 * \brief {brief}
 *
{banner}
*/
"""

SUMMARY_COMMENT_TEMPLATE = r"""/**
{banner}
 * \brief Summary of {title} registers
 * see content definitions in this header file
 *
{banner}
*/
"""

# NOTE: the "CommonAddreses.h" misspelling comes from the reference headers
GLOBAL_COMMENT_TEMPLATE = r"""/**
{banner}
 * \brief Global structure for {title}
 * This points to all the registers, see as arrays if there is either multiplicity
 * or a length in LU RAM.
 * It is addressed via {module}_ADDRESS + PL_BASE_ADDRESS
 * that is defined in CommonAddreses.h.
 *
{banner}
*/
"""

# =====================================================================
# "#define" lines of the module headers
# =====================================================================
DEFINE_TOTAL_SIZE = "TOTAL_SIZE"
DEFINE_PAYLOAD_MULTIPLY = "PAYLOAD_MULTIPLY"
DEFINE_PADDING_MULTIPLE = "PADDING_TO_NEXT_MULTIPLE_ADDRESS"
# a module whose LU RAMs do not all share one length gets a numbered
# define per distinct length: LENGTH_OF_LU_RAM_REGISTER_1, ..._2, ...
DEFINE_LU_RAM_LENGTH = "LENGTH_OF_LU_RAM_REGISTER"
DEFINE_PADDING_AFTER_LU_RAM = "PADDING_TO_NEXT_REGISTER_AFTER_LU_RAM"
DEFINE_PADDING_REGISTERS = "PADDING_TO_NEXT_REGISTERS_ADDRESS"
DEFINE_MODULE_ID = "MODULE_ID"

# one line doxygen comment placed right above each define
DEFINE_COMMENTS = {
    DEFINE_TOTAL_SIZE:
        "size in bytes of the first 2 common registers plus the specific "
        "ones,without counting molteplicity",
    DEFINE_PAYLOAD_MULTIPLY:
        "how many times the registers will be replicated, i.e. how many "
        "parallel tasks",
    DEFINE_PADDING_MULTIPLE:
        "size in bytes of the padding at end of sequence of the registers "
        "to match next sequence of registers (see multiply above)",
    DEFINE_LU_RAM_LENGTH:
        "Length of the register as an array",
    DEFINE_PADDING_AFTER_LU_RAM:
        "size in bytes of the padding at end of sequence of the registers "
        "to match next array of registers",
    DEFINE_PADDING_REGISTERS:
        "size in bytes of the padding at end of the multiple registers to "
        "match next set of registers",
    DEFINE_MODULE_ID:
        "version of the XML configuration file",
}

# the define name is "<MODULE>_" plus the suffix left justified to these
# widths, so that all the values are aligned to the same column; the odd
# widths of the names longer than 33 reproduce the reference headers
DEFINE_FIELD_WIDTHS = {
    DEFINE_TOTAL_SIZE: 33,
    DEFINE_PAYLOAD_MULTIPLY: 33,
    DEFINE_PADDING_MULTIPLE: 33,
    DEFINE_LU_RAM_LENGTH: 33,
    DEFINE_PADDING_AFTER_LU_RAM: 39,
    DEFINE_PADDING_REGISTERS: 34,
    DEFINE_MODULE_ID: 33,
}

# =====================================================================
# C code layout
# =====================================================================
C_WORD_TYPE = "uint32_t"
C_BYTE_TYPE = "uint8_t"
UNION_SUFFIX = "_u"
STRUCT_SUFFIX = "_s"
UNION_RAW_MEMBER = "u32"                 # the "uint32_t u32;" member

INDENT = "    "                          # union / struct bodies
FIELD_INDENT = INDENT * 2                # bit-field lines
FIELD_NAME_WIDTH = 19                    # bit-field name column
FIELD_BITS_WIDTH = 2                     # bit amount, ":%2d;"
MEMBER_TYPE_WIDTH = 49                   # member type column in structs
PADDING_MEMBER_GAP = 8                   # spaces after "uint8_t" in the
                                         # padding members of group structs

COMMENT_OPEN = "/**< "
COMMENT_CLOSE = "  */"
COMMENT_TEXT_WIDTH = 53                  # wrap width of field descriptions
COMMENT_CONTINUATION_COLUMN = 48         # indent of the wrapped lines

RES_FIELD = "res"                        # bit padding inside a register
RES_DESCRIPTION = "Padding"              # its fixed description
RESERVED_FIELD = "reserved"              # bytes between registers
PADDING_FIELD = "paddingToNextRegister"  # bytes closing a multiplied group
                                         # or joining two groups
PADDING_FIELD_LU_RAM = "paddingToNextRegister1"  # bytes after the LU RAM

BLANKS_BETWEEN_BLOCKS = 1                # empty lines between unions
BLANKS_BEFORE_STRUCT = 2                 # before summary / global structs

# =====================================================================
# static names: pieces that cannot be derived from the XML content
# =====================================================================
# group structs: {(system, group index): (struct tag, member name, title)};
# the title is used in "Summary of <title> registers"; None means the
# default title, i.e. the module title plus the group number
GROUP_NAMES = {
    ("TIMER", 0): ("FpgaTimerRegisters_s", "fpgaTimerRegisters", None),
    ("PRACH_CLUSTER_SCHEDULE", 0): ("RachTaskReg_s", "rachTaskReg", None),
    ("CELL_CONFIGURATION", 0): ("CellCfgReg_s", "cellCfgReg", None),
    ("CELL_CONFIGURATION", 1): ("CellCfgRegUt_s", "cellCfgRegUt",
                                "Cell Configuration Ut"),
    ("DL_CLUSTER_PB_SCHEDULE", 0): ("DlTaskRegisters_s", "dlTaskRegisters",
                                    "Dl Task"),
    # no reference header available: names assumed symmetrical to DL
    ("UL_CLUSTER_PB_SCHEDULE", 0): ("UlTaskRegisters_s", "ulTaskRegisters",
                                    "Ul Task"),
}
# fallback when a (system, group) is not listed above: CamelCase(system)
# plus this word, plus the group number from the second group on, like
# CELL_TIMING -> CellTimingReg_s / CellTimingReg2_s
DEFAULT_GROUP_BASENAME = "Reg"

# suffix appended to the union/struct type names of every register of the
# given group, e.g. UT_TEST_CONFIG1 -> union UtTestConfig1Ut_u
GROUP_TYPE_SUFFIXES = {
    ("CELL_CONFIGURATION", 1): "Ut",
}

# group-struct member names not following the camelCase(register) rule
MEMBER_NAME_OVERRIDES = {
    ("TIMER", "STATUS0"): "statusWord0",
    ("TIMER", "STATUS1"): "statusWord1",
    ("TIMER", "STATUS2"): "statusWord2",
    ("TIMER", "STATUS3"): "statusWord3",
    ("CELL_TIMING", "CELL_TIMING_CONFIG1"): "cellTimingConfigWord1",
}

# =====================================================================
# CommonAddresses.h (generated from top.xml)
# =====================================================================
TOP_SYSTEM_NAME = "TOP"
COMMON_ADDRESSES_FILE = "CommonAddresses.h"

PL_BASE_ADDRESS_NAME = "PL_BASE_ADDRESS"
PL_BASE_ADDRESS_VALUE = "0xA0000000"       # PS view of the PL register space
PL_BASE_ADDRESS_COMMENT = "Programmable logic register base address"

ADDRESS_DEFINE_SUFFIX = "_ADDRESS"
ADDRESS_DEFINE_WIDTH = 28                # name column of the defines
ADDRESS_COMMENT = "%s shift address"
ADDRESS_VALUE_FORMAT = "0x%08X"
